name: ReportHacker
version: 1.0.0
author: MCrafters
api: [1.0.0]
main: ReportHacker\Main
commands:
  reporthacker:
    description: Report A Hacker/Modder!
    usage: "/report <player>"
    permission: reporthacker.command
    aliases: [report, rpt]
permissions:
  reporthacker.command:
    default: true
